codecov:
  strict_yaml_branch: master
coverage:
  status:
    project:
      default:
        threshold: 0
        if_no_uploads: failure
        if_ci_failed: failure
    patch:
      default:
        target: 100
        only_pulls: true
    changes:
      default:
        if_no_uploads: failure
        if_ci_failed: failure
        only_pulls: true
comment:
  layout: "header, diff, changes"
